AppBundle\Entity\Persona:
    type: entity
    table: persona
    repositoryClass: AppBundle\Repository\PersonaRepository
    indexes:
        usuario_id:
            columns:
                - usuario_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        apellido:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    manyToOne:
        usuario:
            targetEntity: Usuario
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                usuario_id:
                    referencedColumnName: id
            orphanRemoval: false
    #··················· Nueva Relacion (P1)         
    oneToMany:
        telefono:
            targetEntity: Telefono
            mappedBy: persona
            cascade: ["persist"]
        persCurs:
            targetEntity: PersCurs
            mappedBy: persona
            cascade: ["persist"]
    lifecycleCallbacks: {  }
