AppBundle\Entity\Telefono:
    type: entity
    table: telefono
    indexes:
        persona_id:
            columns:
                - persona_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        numero:
            type: string
            nullable: false
            length: 11
            options:
                fixed: false
    manyToOne:
        persona:
            targetEntity: Persona
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: telefono
            joinColumns:
                persona_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
