app_homepage:
    path: /
    defaults: { _controller: AppBundle:Default:index }

# Login    
login:
    path: /login
    defaults: { _controller: AppBundle:Usuario:login }

login_check:
    path: /login_check
 
logout:
    path: /logout

# Cursos
Blog_index_cursos:
    path: /cursos
    defaults: { _controller: AppBundle:Cursos:index }

Blog_add_cursos:
    path: /cursos/add
    defaults: { _controller: AppBundle:Cursos:add }

Blog_delele_cursos:
    path: /cursos/delete/{id}
    defaults: { _controller: AppBundle:Cursos:delete }

Blog_edit_cursos:
    path: /cursos/edit/{id}
    defaults: { _controller: AppBundle:Cursos:edit }

# Telefonos
Blog_index_telefonos:
    path: /telefonos
    defaults: { _controller: AppBundle:Telefono:index }

Blog_add_telefonos:
    path: /telefonos/add
    defaults: { _controller: AppBundle:Telefono:add }

Blog_delele_telefonos:
    path: /telefonos/delete/{id}
    defaults: { _controller: AppBundle:Telefono:delete }

Blog_edit_telefonos:
    path: /telefonos/edit/{id}
    defaults: { _controller: AppBundle:Telefono:edit }

# Persona
Blog_add_persona:
    path: /persona/add
    defaults: { _controller: AppBundle:Persona:add }

Blog_index_persona:
    path: /persona
    defaults: { _controller: AppBundle:Persona:index }

Blog_delete_persona:
    path: /persona/delete/{id}
    defaults: { _controller: AppBundle:Persona:delete }

Blog_edit_persona:
    path: /persona/edit/{id}
    defaults: { _controller: AppBundle:Persona:edit }


######

Blog_new_cursos:
    path: /cursos/new/{id}
    defaults: { _controller: AppBundle:Cursos:new }
