AppBundle\Entity\Usuario:
    properties:
        user:
            - NotBlank: {message: "No puede estar vacio"}
            - Length:
                  min: 3
                  minMessage: "Su Usuario debe tener mas de 3 caracteres"
        password:
            - NotBlank: {message: "No puede estar vacio"}
            - Length:
                  min: 4
                  minMessage: "Su Contrasea debe tener mas de 4 caracteres"


AppBundle\Entity\Cursos:
    properties:
        nombreCurso:
            - NotBlank: {message: "No puede estar vacio"}
            - Length:
                  min: 3
                  minMessage: "Debe tener mas de 3 caracteres"
        tutor:
            - NotBlank: {message: "No puede estar vacio"}
            - Length:
                  min: 3
                  minMessage: "Debe tener mas de 3 caracteres"
        descripcion:
            - NotBlank: {message: "No puede estar vacio"}
            - Length:
                  min: 3
                  minMessage: "Debe tener mas de 3 caracteres"

AppBundle\Entity\Persona:
    properties:
        nombre:
            - NotBlank: {message: "No puede estar vacio"}
            - Length:
                  min: 3
                  minMessage: "Debe tener mas de 3 caracteres"
        apellido:
            - NotBlank: {message:"No puede estar vacio"}
            - Length:
                  min: 3
                  minMessage: "Debe tener mas de 3 caracteres"

AppBundle\Entity\Telefono:
    properties:
        numero:
            - NotNull: {message: "No puede estar vacio"}
            - Type:
                type: numeric
                message: "Solo Numeros"
            - Length:
                min: 7
                minMessage: "Debe tener mas de 7 caracteres"


        